### ISSUE TITLE
Have you ever published to npm?

### ISSUE THREAD

**Issue by chinesedfan** [PylonFE/Pylon#1]
`npm info Pylon` returns 404.

**Comment by ShanaMaid** [comment]
@chinesedfan 
npm install Pylonn

**Comment by chinesedfan** [comment]
@ShanaMaid Did you publish in private registry? Neither `Pylon` nor `Pylonn` is not found.

**Comment by ShanaMaid** [comment]
sorry , that is
```
npm install pylonn
```

**Comment by chinesedfan** [comment]
Good, it works now, although a little strange because the project name is `PylonFE/Pylon`.

**Comment by ShanaMaid** [comment]
hah!
